name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: "0 6 * * 3"

jobs:

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    env:
      PHAN_ALLOW_XDEBUG: 0
      PHAN_DISABLE_XDEBUG_WARN: 1

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: pecl
          extensions: ast, gd, exif, gettext, mbstring

      - name: "Update dependencies with composer"
        run: composer update --no-interaction --no-ansi --no-progress --no-suggest

      - name: "Run phan"
        run: php vendor/bin/phan


  build-docs:
    name: "Build and publish Docs"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
          tools: phpDocumentor
          extensions: gd, exif, gettext, mbstring

      - name: "Build Docs"
        run: phpdoc --config=phpdoc.xml

      - name: "Publish Docs to gh-pages"
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc
          clean: true


  tests:
    name: "Unit Tests"

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:

        - name: "Checkout"
          uses: actions/checkout@v3

        - name: "Install PHP"
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            coverage: pcov
            extensions: gd, exif, gettext, mbstring

        - name: "Install Composer dependencies"
          run: composer update --no-ansi --no-interaction --no-progress --no-suggest

        - name: "Run tests with phpunit"
          run: php vendor/bin/phpunit --configuration=phpunit.xml

#        - name: "Send code coverage report to Codecov.io"
#          uses: codecov/codecov-action@v1
#          with:
#            token: ${{ secrets.CODECOV_TOKEN }}
